GET http://localhost:8080/api/v1/comments
### Find all comments

### Save comment by userId and ComicDetailId
POST http://localhost:8080/api/v1/comments
Content-Type: application/json

{
"text":"Truyen nhu quan que",
"userId":1,
"comicDetailId":2
}
### Update  comment by userId and ComicDetailId
 PUT http://localhost:8080/api/v1/comments/1
Content-Type: application/json

{
  "text":"Truyen nhu quan que nguoi ta",
  "userId":1,
  "comicDetailId":2
}
